"""Initial migration.

Revision ID: 4af0aad0df64
Revises: 
Create Date: 2023-12-04 19:58:16.025580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af0aad0df64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('city_uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('geo_location_latitude', sa.Float(), nullable=False),
    sa.Column('geo_location_longitude', sa.Float(), nullable=False),
    sa.Column('beauty', sa.Enum('Ugly', 'Average', 'Gorgeous', name='beauty_enum'), nullable=False),
    sa.Column('population', sa.BIGINT(), nullable=False),
    sa.Column('allied_cities', sa.ARRAY(sa.UUID()), nullable=True),
    sa.PrimaryKeyConstraint('city_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    # ### end Alembic commands ###
